### ISSUE TITLE
Add Copy traits to Feature and Geometry struct

### ISSUE THREAD

**Issue by Farkal** [georust/geojson#110]
I would like to push all the geometries of a geojson inside RTree -> https://github.com/Stoeoef/rstar
But i can't just take feature and implement rstar::Point trait because the Copy trait is not present on Feature, same issue with Geometry :disappointed: 

If you know an easy way i can add all my geojson objects to that RTree, I am very interested :smile:

**Comment by antoine-de** [comment]
Are you sure you want to store a Geojson in your rtree and not something from [geo_types](https://crates.io/crates/geo-types) ?

anyway the objects you want to add implement `Clone`, so you can just `.clone()` them while inserting them (if you don't own them, and thus can't move them)

**Comment by urschrei** [comment]
You can convert a GeoJSON feature into a [`geo_type`](https://docs.rs/geo_types/) by using `try_into()`, which will yield an `Option<_>`

Something like

    // ensure you've specified geo-types 0.4 in Cargo.toml
    use geo_types::{Point, Linestring, Polygon};
    // geojson_polygon is assumed to be a GeoJSON polygon type
    let geo_polygon: geo_types::Polygon<f64> = geojson_polygon.try_into().unwrap();
You can then use `geo_polygon` with `rstar`, as it implements the requisite traits, and convert back again when you're ready to write it out etc.

**Comment by Farkal** [comment]
Thank you very much for your quick answer !
Your solution help me a lot but there still an issue with the properties of a feature, i would like to be able to retrieve from witch feature a point came when i find it in RTree. My current solution is to store the index of the geojson feature and then get it's properties from the geojson by the index. 
The best solution would be to store the feature properties with the point but any dynamic type cannot implement the copy trait and i need it for the rstar::Point trait -> https://docs.rs/rstar/0.2.0/rstar/trait.Point.html

**Comment by frewsxcv** [comment]
Many types within `Geometry` use `Vec` which is a _heap_ allocated data structure, for example `LineString`. `Copy` can only be implemented for _stack_ allocated data structures like `f64` or tuples.
