### ISSUE TITLE
How do you convert Geometry to String?

### ISSUE THREAD

**Issue by stepankuzmin** [georust/geojson#112]
Hi there! I want to convert `Geometry` to `String` like this:

```rust
let geometry = Geometry::new(Value::LineString(route));
geometry.to_string()
```

But I'm getting an Error:

```shell
the method `to_string` exists but the following trait bounds were not satisfied:
           `geojson::Geometry : std::string::ToString`
```

I'm using `serde_json::to_string(&geometry)?` for now, but I'm not sure if it's a proper way.

**Comment by urschrei** [comment]
Hmm looks like we haven't implemented `Display` for `Feature` and `Geometry`. See #113
