### ISSUE TITLE
Re-export ergonomics when using conversions

### ISSUE THREAD

**Issue by urschrei** [georust/geojson#121]
Because the `From`, `TryFrom`, `TryInto` conversions are only implemented for the primitive types in `geo_types`, you run into type mismatches if you then attempt to use functionality from `geo`, because it's all implemented on the re-exported types.

I have no idea how to easily fix this, but it's a big ergonomics issue – @frewsxcv any ideas?

**Comment by frewsxcv** [comment]
Did you get this resolved @urschrei ? If I had to guess, it might be due to mismatched versions of `geo-types` dependencies

**Comment by urschrei** [comment]
Yep, it was in conjunction with `[patch]`ed versions of either crate – if you specify HEAD from Github in cargo, you get type mismatches, whereas the published crates work fine together.

**Comment by frewsxcv** [comment]
Ah yeah, that's always frustrating. Glad you got it sorted though!
