### ISSUE TITLE
Minor Q: Should 0.18.0 be on Github releases?

### ISSUE THREAD

**Issue by nick-parker** [georust/geojson#126]
I'm poking around various geo crates trying to get a PR together to move rust-geo-boolean-ops onto the latest version of geo-types without breaking tons of geojson based tests.

It looks like geojson's latest version on crates.io is 0.18.0, but the releases on this Github page only go to 0.17.0. I came here first so for a moment I thought the project was inactive, but it turns out it's very active!

Not urgent at all and barely matters, I just wanted to flag this in case your deployment pipeline's gone wonky or something.

**Comment by frewsxcv** [comment]
thanks for flagging! added the 0.18.0, and now it shows up on the releases page: https://github.com/georust/geojson/releases
