### ISSUE TITLE
Implement conversions for Line, GeometryCollection, Rect, Triangle

### ISSUE THREAD

**Issue by urschrei** [georust/geojson#133]
Currently, this causes a run-time `panic!()`, which is not great. `Line`, `Triangle` and `Rect` should be easy to implement, <s>but what about `GeometryCollection`?</s>

**Comment by urschrei** [comment]
`Line` maps to GeoJSON `LineString`
`Triangle` and `Rect` map to GeoJSON `Polygon`
`GeometryCollection` maps to GeoJSON `GeometryCollection`

**Comment by frewsxcv** [comment]
Relevant code that needs to change:

https://github.com/georust/geojson/blob/f394a5b3424c2b44e5e762d5b98787854b1edd73/src/conversion/from_geo_types.rs#L101-L121

We should stop using `_` as a matching pattern here and make it exhaustive.
