### ISSUE TITLE
GeoJSON::from(geo:Geometry) / GeoJSON::from(geo:Polygon) / etc

### ISSUE THREAD

**Issue by michaelkirk** [georust/geojson#163]
(Pulled out of the discussion https://github.com/georust/geojson/pull/162#issuecomment-810416236)

The GeoJSON API could be more intuitive for the common case of wanting to serialize a bunch of geometric data, without wanting to leverage foreign members or other geojson features.

Specifically, I propose the following methods work for all geo_types::Geometry variants:

```
let a_polygon: = GeoJson::from(geo::Polygon::new(...))

let another_polygon: GeoJson = GeoJson::from(geo::Geometry::Polygon(Polygon::new(...)))

let geometry_collection: GeoJson = GeoJson::from_iter(vec![Polygon::new(...),])
```

With an implementation something like:
```
impl<T: geo_types::CoordFloat> FromIterator<geo_types::Polygon<T>> for GeoJson {
    fn from_iter<P>(polygons: P) -> Self
        where P: IntoIterator<Item = geo_types::Polygon<T>>
    { 
        let gc = geo_types::GeometryCollection::from_iter(polygons);
        let fc = FeatureCollection::from(&gc);
        GeoJson::from(fc)
    }
} 
```

**Comment by michaelkirk** [comment]
@urschrei - just so we're not duplicating work - were you planning to take a go at this? Otherwise I will.

**Comment by urschrei** [comment]
Happy for you to take it!
