### ISSUE TITLE
Release 0.22.1

### ISSUE THREAD

**Issue by michaelkirk** [georust/geojson#168]
So far, no breaking changes have been merged, so we can just do a minor release - no breaking changes this time. 

Anyone else want to get something in?

Otherwise I'll plan to release as-is in ~72 hours (Monday morning PDT).

**Comment by michaelkirk** [comment]
Oh 😅 

> error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.

Would someone from @georust/geojson-publishers run `cargo publish` and tag?

Or, alternatively, you could add me to @georust/geojson-publishers

**Comment by frewsxcv** [comment]
![Screen Shot 2021-04-19 at 6 41 35 PM](https://user-images.githubusercontent.com/416575/115312200-e8295800-a13e-11eb-856d-874e01461045.png)

**Comment by michaelkirk** [comment]
I have proven my worth by botching my first release. 🤦 

I released 0.22.1 without the most recent PR from my local stale master. I followed up a couple minutes later with the 0.22.2 release, based on the stale master.

For the unlikely person who updated geojson in the few minutes between 0.22.1 and 0.22.2, there shouldn't be any problem, it just excludes #165. 

https://github.com/georust/geojson/compare/0.22.1...0.22.2

**Comment by frewsxcv** [comment]
no worries! any interest in yanking that release? https://doc.rust-lang.org/cargo/commands/cargo-yank.html

**Comment by michaelkirk** [comment]
Sure - done.
