### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by urschrei** [georust/geojson#172]
As mentioned in a previous PR (and as @rmanoka mentioned wrt `Value`) our docs are extensive but unclear, because we're trying to address both high-level (with a growing list of convenience functions and API improvements), and lower-level (e.g. geojson as a computation pipeline component / FFI component) use-cases. We have lots of docs and examples, they're just intermingled in ways that make certain aspects of the crate difficult to discover.

I would dearly like to come up with a (hopefully simple) reorganisation strategy that splits these concerns and addresses them in a way that makes it more obvious where one has to "go" to figure out how to use the crate, depending on one's use case.

Apart from the motivation laid out above, my sense is that geojson is one of the more (if not the most) popular crates in the geo ecosystem, and public-facing improvements to it will hopefully benefit the project (such as it is) more generally.

What do people think?

**Comment by michaelkirk** [comment]
Giving the docs some much needed attention would be great!

> splits these concerns and addresses them in a way that makes it more obvious where one has to "go" to figure out how to use the crate

I'm not sure I entirely understand what the two separate use cases are. I do agree that the crate seems to be harder to pick up than I'd like (especially for those new to rust), and no doubt the documentation could be better organized.

> Apart from the motivation laid out above, my sense is that geojson is one of the more (if not the most) popular crates in the geo ecosystem, and public-facing improvements to it will hopefully benefit the project (such as it is) more generally.

💯

**Comment by rmanoka** [comment]
Yes, I too agree that the docs could be a bit more streamlined.  For concreteness, here are the specific points I would like to see addressed:

1. Clarify integration with `serde_json`:  we only advertise the `str::parse` and `ToString::to_string` methods, but typically the `{from,to}_writer` and related methods are more useful and provide greater flexibility.  Also, the crate doc. suggests that `serde` is optional, but we rely quite heavily on it.  Is this an artifact from a previous version of the crate?

2. Modularize top-level crate doc:  we have covered most of the crate functionality, but it is all mentioned at the top-level.  This makes it difficult to quickly figure what to do for a specific use-case which is typically what users want out of the docs.  Would be better to be move things around so the top-level doc is concise, and points to the specific structs and their docs for the respective functionality.

I could work on a PR for this, but docs are also a matter of taste, so wanted to get some more opinions before refactoring things around.

**Comment by urschrei** [comment]
1. AFAIK there was an effort to keep things non-serde-specific at one point, but we do already depend on it quite heavily, as you say, so maybe it's OK to have it as a dep? @frewsxcv ISTR this was discussed before (a long time ago, though…)

2. I'm very happy for examples / docs to be moved around and only mentioned at the top level where relevant – I agree that the docs are quite top-heavy.

**Comment by michaelkirk** [comment]
> Also, the crate doc. suggests that serde is optional, but we rely quite heavily on it. Is this an artifact from a previous version of the crate?

My read is that the docs are just out of date.

see here for a similar issue: https://github.com/georust/geojson/issues/78

Looks like it was originally dropped around 2017: https://github.com/georust/geojson/pull/58
