### ISSUE TITLE
Converting simple `FeatureCollection` to `geo-types` causes an error

### ISSUE THREAD

**Issue by frewsxcv** [georust/geojson#193]
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "GeometryCollection",
        "geometries": [
          {
            "type": "Polygon",
            "coordinates": [
              [
                [1.0, 1.0],
                [2.0, 2.0],
                [3.0, 1.0],
                [1.0, 1.0]
              ]
            ]
          }
        ]
      },
      "properties": {}
    }
  ]
}
```

Loading this into `geojson` is fine, but when we try to convert to `geo-types` we get this error:

```
InvalidGeometryConversion(GeometryCollection([Geometry { bbox: None, value: Polygon([[[1.0, 1.0], [2.0, 2.0], [3.0, 1.0], [1.0, 1.0]]]), foreign_members: None }]))
```

**Comment by frewsxcv** [comment]
Does this need a `GeometryCollection` branch?

https://github.com/georust/geojson/blob/af3b1c35f92ed4c1f0be9dd56adb99e9af373dd3/src/conversion/to_geo_types.rs#L169

**Comment by michaelkirk** [comment]
Can you share more of the code you're using to this this error? 

I can't immediately reproduce it - this runs: https://github.com/georust/geojson/compare/mkirk/fc-to-geo?expand=1

**Comment by michaelkirk** [comment]
Ah, I figured it out! You can hit it when converting a single feature rather than the entire feature collection. I pushed a new commit to:  https://github.com/georust/geojson/compare/mkirk/fc-to-geo?expand=1
