### ISSUE TITLE
InvalidGeometryConversion should have "expected" vs. "found" types.

### ISSUE THREAD

**Issue by michaelkirk** [georust/geojson#201]
Currently when trying to convert from a geojson geometry to an incompatible geo-type (e.g. a Point to a LineString) we use this error:

```
#[error("Encountered a mismatch when converting to a Geo type: `{0}`")]
InvalidGeometryConversion(geojson::Geometry::Value),
```

But instead, I think it'd be more helpful as
```
#[error("Expected geometry type: `{expected_type}`, but found: `{found_type}`")]
InvalidGeometryConversion { expected_type: &'static str, found_type: &'static str }
```

- avoids a very long error message in the case of printing out a large geometry
- it's a more useful error message in my opinion
- no longer requires ownership of the geometry value, paving the way for borrowed geometry conversions

**Comment by metasim** [comment]
I think this is a good idea. The former limits control over resource usage just to print an error. Could blow up log messages, etc.

**Comment by metasim** [comment]
Another options would be to still allow the incompatible geometry to remain as-is so it's available to error handlers, but change the error reporting message to not `Display` the value.

**Comment by urschrei** [comment]
In the absence of data to the contrary, I don't think we have to be maximally flexible in our error handling when it comes to conversions (see #176, #197) and I'd be fine with just changing it rather than retaining it without Display.
