### ISSUE TITLE
hyperlink fails on doc.rs

### ISSUE THREAD

**Issue by JosiahParry** [georust/geojson#216]
https://github.com/georust/geojson/blob/aa4c733de9409a0475f34f5f6e401afc1cad240a/src/lib.rs#L41

This hyper link redirects to the geojson documentation homepage
.

**Comment by frewsxcv** [comment]
This was fixed in https://github.com/georust/geojson/commit/760969ab75a2845c705a32e34c8f7ebbf7e227a9
