### ISSUE TITLE
feature flag to interop with `rust::geo`

### ISSUE THREAD

**Issue by kraktus** [georust/geojson#239]
Hello, thanks for the great crate.

A nice-to-have feature-flag would be to allow directly converting `geojson::PolygonType` to `geo::Polygon`. I don't know in which create it should live. I assume it's reasonably frequent to use those two together

for now doing that: 

```rust
fn vec_to_line(vec: &Vec<Vec<f64>>) -> LineString<f64> {
    vec.iter()
        .map(|coord| (coord[0], coord[1]))
        .collect::<Vec<_>>()
        .into()
}

fn polygon_to_polygon(polygon: &PolygonType) -> geo::Polygon {
    let mut copy_vec = polygon.clone();
    let holes = copy_vec.split_off(1);
    let line = vec_to_line(&copy_vec[0]);

    geo::Polygon::new(line, holes.iter().map(vec_to_line).collect())
}
```

**Comment by lnicola** [comment]
https://docs.rs/geojson/latest/geojson/#use-geojson-with-other-crates-by-converting-to-geo-types

**Comment by kraktus** [comment]
Thanks 👍
