### ISSUE TITLE
Implement changes in RFC 7946

### ISSUE THREAD

**Issue by frewsxcv** [georust/geojson#53]
http://www.macwright.org/2016/11/07/the-geojson-ietf-standard.html

**Comment by frewsxcv** [comment]
https://tools.ietf.org/html/rfc7946

**Comment by frewsxcv** [comment]
We need to enforce that `Polygon`s from the `geo-type` crate are oriented the right way when converted to `Value`s, as per:

>   A linear ring MUST follow the right-hand rule with respect to the
      area it bounds, i.e., exterior rings are counterclockwise, and
      holes are clockwise.


https://tools.ietf.org/html/rfc7946#section-3.1.6

**Comment by frafra** [comment]
Right-hand rule is not enforced by the software at the moment, but it should: https://gis.stackexchange.com/a/259957/162589

**Comment by frewsxcv** [comment]
> Right-hand rule is not enforced by the software at the moment, but it should: https://gis.stackexchange.com/a/259957/162589

Yep, thanks for calling that out. An attempt at fixing this was done in https://github.com/georust/geojson/pull/117
